import { Request, Response } from 'express';
import { StatusCodes } from 'http-status-codes';
import * as service from '../services/academicOps.service.js';
const contextFrom = (request: Request) => ({ userId: request.auth?.userId, institutionId: request.auth?.institutionId, role: request.auth?.role });
const ok = async (response: Response, data: unknown, status = StatusCodes.OK) => response.status(status).json({ success: true, data });
export const options = async (req: Request, res: Response) => ok(res, await service.listOptions(contextFrom(req)));
export const listExams = async (req: Request, res: Response) => ok(res, await service.listExamTimetables(contextFrom(req)));
export const createExam = async (req: Request, res: Response) => ok(res, await service.createExamTimetable(contextFrom(req), req.body), StatusCodes.CREATED);
export const updateExam = async (req: Request, res: Response) => ok(res, await service.updateExamTimetable(contextFrom(req), req.params.id, req.body));
export const deleteExam = async (req: Request, res: Response) => ok(res, await service.deleteExamTimetable(contextFrom(req), req.params.id));
export const listClassTimetable = async (req: Request, res: Response) => ok(res, await service.listClassTimetables(contextFrom(req)));
export const createClassTimetable = async (req: Request, res: Response) => ok(res, await service.createClassTimetable(contextFrom(req), req.body), StatusCodes.CREATED);
export const updateClassTimetable = async (req: Request, res: Response) => ok(res, await service.updateClassTimetable(contextFrom(req), req.params.id, req.body));
export const deleteClassTimetable = async (req: Request, res: Response) => ok(res, await service.deleteClassTimetable(contextFrom(req), req.params.id));
export const listNotices = async (req: Request, res: Response) => ok(res, await service.listNotices(contextFrom(req)));
export const createNotice = async (req: Request, res: Response) => ok(res, await service.createNotice(contextFrom(req), req.body), StatusCodes.CREATED);
export const updateNotice = async (req: Request, res: Response) => ok(res, await service.updateNotice(contextFrom(req), req.params.id, req.body));
export const deleteNotice = async (req: Request, res: Response) => ok(res, await service.deleteNotice(contextFrom(req), req.params.id));
export const listResources = async (req: Request, res: Response) => ok(res, await service.listResources(contextFrom(req)));
export const createResource = async (req: Request, res: Response) => ok(res, await service.createResource(contextFrom(req), req.body), StatusCodes.CREATED);
export const deleteResource = async (req: Request, res: Response) => ok(res, await service.deleteResource(contextFrom(req), req.params.id));
export const listLabs = async (req: Request, res: Response) => ok(res, await service.listLabs(contextFrom(req)));
export const createLab = async (req: Request, res: Response) => ok(res, await service.createLab(contextFrom(req), req.body), StatusCodes.CREATED);
export const updateLab = async (req: Request, res: Response) => ok(res, await service.updateLab(contextFrom(req), req.params.id, req.body));
export const deleteLab = async (req: Request, res: Response) => ok(res, await service.deleteLab(contextFrom(req), req.params.id));
export const listLabTimetable = async (req: Request, res: Response) => ok(res, await service.listLabTimetables(contextFrom(req)));
export const createLabTimetable = async (req: Request, res: Response) => ok(res, await service.createLabTimetable(contextFrom(req), req.body), StatusCodes.CREATED);
export const deleteLabTimetable = async (req: Request, res: Response) => ok(res, await service.deleteLabTimetable(contextFrom(req), req.params.id));
export const portalFeed = async (req: Request, res: Response) => ok(res, await service.portalAcademicFeed(contextFrom(req)));
export const dashboardSummary = async (req: Request, res: Response) => ok(res, await service.dashboardSummary(contextFrom(req)));
