import { Router, type Router as ExpressRouter } from 'express';
import { Role } from '@prisma/client';
import * as controller from '../controllers/academicOps.controller.js';
import { authenticate, requireRole } from '../middleware/auth.js';
import { writeRateLimiter } from '../middleware/rateLimit.js';
import { asyncHandler } from '../utils/asyncHandler.js';

export const academicOpsRouter: ExpressRouter = Router();
academicOpsRouter.use(authenticate);
const admin = [Role.ADMIN, Role.SUPER_ADMIN, Role.HOD];
const adminOrTeacher = [Role.ADMIN, Role.SUPER_ADMIN, Role.HOD, Role.TEACHER, Role.PROFESSOR];
academicOpsRouter.get('/academic-ops/options', requireRole(...adminOrTeacher), asyncHandler(controller.options));
academicOpsRouter.get('/academic-ops/dashboard-summary', requireRole(...admin), asyncHandler(controller.dashboardSummary));
academicOpsRouter.get('/academic-ops/exams', requireRole(...adminOrTeacher), asyncHandler(controller.listExams));
academicOpsRouter.post('/academic-ops/exams', requireRole(...admin), writeRateLimiter, asyncHandler(controller.createExam));
academicOpsRouter.patch('/academic-ops/exams/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.updateExam));
academicOpsRouter.delete('/academic-ops/exams/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.deleteExam));
academicOpsRouter.get('/academic-ops/class-timetable', requireRole(...adminOrTeacher), asyncHandler(controller.listClassTimetable));
academicOpsRouter.post('/academic-ops/class-timetable', requireRole(...admin), writeRateLimiter, asyncHandler(controller.createClassTimetable));
academicOpsRouter.patch('/academic-ops/class-timetable/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.updateClassTimetable));
academicOpsRouter.delete('/academic-ops/class-timetable/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.deleteClassTimetable));
academicOpsRouter.get('/academic-ops/notices', requireRole(...adminOrTeacher), asyncHandler(controller.listNotices));
academicOpsRouter.post('/academic-ops/notices', requireRole(...admin), writeRateLimiter, asyncHandler(controller.createNotice));
academicOpsRouter.patch('/academic-ops/notices/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.updateNotice));
academicOpsRouter.delete('/academic-ops/notices/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.deleteNotice));
academicOpsRouter.get('/academic-ops/resources', requireRole(...adminOrTeacher), asyncHandler(controller.listResources));
academicOpsRouter.post('/academic-ops/resources', requireRole(...adminOrTeacher), writeRateLimiter, asyncHandler(controller.createResource));
academicOpsRouter.delete('/academic-ops/resources/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.deleteResource));
academicOpsRouter.get('/academic-ops/labs', requireRole(...adminOrTeacher), asyncHandler(controller.listLabs));
academicOpsRouter.post('/academic-ops/labs', requireRole(...admin), writeRateLimiter, asyncHandler(controller.createLab));
academicOpsRouter.patch('/academic-ops/labs/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.updateLab));
academicOpsRouter.delete('/academic-ops/labs/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.deleteLab));
academicOpsRouter.get('/academic-ops/lab-timetable', requireRole(...adminOrTeacher), asyncHandler(controller.listLabTimetable));
academicOpsRouter.post('/academic-ops/lab-timetable', requireRole(...admin), writeRateLimiter, asyncHandler(controller.createLabTimetable));
academicOpsRouter.delete('/academic-ops/lab-timetable/:id', requireRole(...admin), writeRateLimiter, asyncHandler(controller.deleteLabTimetable));
academicOpsRouter.get('/portal/academic-feed', requireRole(Role.STUDENT, Role.PARENT, Role.TEACHER, Role.PROFESSOR), asyncHandler(controller.portalFeed));
